name : upload


on:
    schedule:
      - cron: "0 */5 * * *"
    push:
      branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       
       - name: Set up Git repository
         uses: actions/checkout@v2
       
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9

       - name: Running
         timeout-minutes: 359
         continue-on-error: true
         env:
            BTOKEN: ${{ secrets.B_TOKEN }}
         run: |
           ls
           pip install -r requirements.txt
           python3 uploadbot.py
